parameters:
    uf.util.email.class: FanPollster\ApplicationBundle\Util\Email

services:
    uf.util.email:
        class: %uf.util.email.class%
        arguments:
            - '@mailer'
            - %uf_util_system_email_username%
            - %uf_util_website_domain%
