parameters:
    uf_util_email_class: Userfriendly\Bundle\UtilityBundle\Utility\Email

services:
    uf.util.email:
        class: %uf_util_email_class%
        arguments:
            - '@mailer'
            - %uf_util_system_email_username%
            - %uf_util_website_domain%
